[package]
name = "code-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
# Dateisystem-Operationen
walkdir = "2.4"                                   # Rekursives Verzeichnis-Traversieren
tokio = { version = "1.36", features = ["full"] } # Async Runtime

# HTTP Requests
reqwest = { version = "0.11", features = ["json"] } # HTTP Client
futures = "0.3"                                     # Async Tools

# JSON Verarbeitung
serde = { version = "1.0", features = ["derive"] } # Serialisierung Framework
serde_json = "1.0"                                 # JSON Implementierung

# Error Handling
anyhow = "1.0"    # Error Handling Vereinfachung
thiserror = "1.0" # Error Type Definitionen

# Logging
tracing = "0.1"            # Logging Framework
tracing-subscriber = "0.3" # Logging Implementation

async-trait = "0.1"
dotenv = "0.15"
