[package]
name = "code-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"
ignore = "0.4"
walkdir = "2.4"
tokio = { version = "1.36", features = ["full"] }

# HTTP Requests
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"

# JSON (de)serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# CLI
clap = { version = "4.5", features = ["derive"] }

async-trait = "0.1"
dotenv = "0.15"

# Date and time handling
chrono = { version = "0.4", features = ["serde"] }
